[package]
name = "csv-reading"
version = "0.1.0"
authors = ["Samrat K S <samrat.ks@soroco.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "*"
csv = "*"