[package]
name = "cli"
version = "0.1.0"
authors = ["Samrat K S <samrat.kashipathi1@gmail.com>"]

[dependencies]
clap = { features = ["yaml"] }
dotenv_codegen = "0.14.0"
ansi_term = "0.12.0"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"